# Generated by Django 3.0.8 on 2020-07-24 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interimaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('nom', models.CharField(max_length=50)),
                ('mail', models.CharField(max_length=50)),
                ('portable', models.CharField(max_length=50)),
                ('date_naissance', models.DateField()),
                ('lieu_naissance', models.DateField()),
                ('adresse', models.CharField(max_length=50)),
                ('mobilite_geographique', models.CharField(max_length=50)),
                ('date_creation', models.DateField()),
                ('ci', models.FileField(upload_to='')),
                ('autres_documents', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_intervention', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('client', models.CharField(max_length=50)),
                ('adresse_client', models.CharField(max_length=50)),
                ('interimaire', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=50)),
            ],
        ),
    ]
