# Generated by Django 3.0.8 on 2020-07-24 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interimaire',
            name='lieu_naissance',
            field=models.CharField(max_length=50),
        ),
    ]
