# Generated by Django 3.0.8 on 2020-07-24 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_auto_20200724_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervention',
            name='interimaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.Interimaire'),
        ),
    ]
