# Generated by Django 3.0.8 on 2020-07-26 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_auto_20200724_2157'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=50)),
                ('nom', models.CharField(max_length=50)),
                ('mail', models.CharField(max_length=50)),
                ('telephone', models.CharField(max_length=50)),
                ('date_naissance', models.DateField()),
                ('lieu_naissance', models.CharField(max_length=50)),
                ('adresse', models.CharField(max_length=50)),
                ('situation_actuelle', models.CharField(max_length=50)),
                ('specialite', models.CharField(max_length=50)),
                ('experience', models.CharField(max_length=50)),
                ('cv', models.FileField(upload_to='')),
                ('lettre_de_motivation', models.FileField(upload_to='')),
                ('date_creation', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='intervention',
            name='cout',
            field=models.FloatField(default=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='intervention',
            name='distance',
            field=models.FloatField(default=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='interimaire',
            name='autres_documents',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='date',
            field=models.DateField(),
        ),
    ]
