# Generated by Django 3.0.8 on 2020-07-26 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_auto_20200726_1317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='intervention',
            old_name='client',
            new_name='nom_client',
        ),
        migrations.RenameField(
            model_name='intervention',
            old_name='type',
            new_name='tel_client',
        ),
    ]
