# Generated by Django 3.0.8 on 2020-08-09 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_auto_20200809_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='miseadisposition',
            name='client',
        ),
        migrations.AddField(
            model_name='miseadisposition',
            name='entreprise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.Entreprise'),
        ),
    ]
